export const sectionToPath: Record<string, string> = {
  'overview': '/dashboard',
  'today': '/today',
  'ai_brain': '/ai-brain',
  'smart_planner': '/smart-planner',
  'placement_os': '/placement-os',
  'learning_os': '/learning-os',
  'roadmap': '/roadmap',
  'ai': '/shayla',
  'ai_settings': '/ai-settings',
  'shayla_memory': '/shayla-memory',
  'ai_playground': '/ai-playground',
  'ai_benchmark': '/ai-benchmark',
  'german': '/german',
  'coding_mentor': '/coding-mentor',
  'career_intelligence': '/career-intelligence',
  'integrations': '/integrations',
  'analytics': '/analytics',
  'reports': '/reports',
  'dsa_tracker': '/dsa-tracker',
  'skillrack': '/skillrack',
  'aptitude': '/aptitude',
  'sql': '/sql',
  'cscore': '/cs-core',
  'projects': '/projects',
  'resume': '/resume',
  'interview_coach': '/interview-coach',
  'applications': '/applications',
  'calendar': '/calendar',
  'placement_calendar': '/placement-calendar',
  'companies': '/companies',
  'skill_tree': '/skill-tree',
  'achievements': '/achievements',
  'history': '/history',
  'settings': '/settings',
  'admin': '/admin',
  'mock_interview_os': '/mock-interview-os',
  'company_intelligence': '/company-intelligence',
  'portfolio_os': '/portfolio-os',
  'ai_mentor': '/ai-mentor',
};

export const pathToSection: Record<string, string> = {
  '/dashboard': 'overview',
  '/overview': 'overview',
  '/today': 'today',
  '/ai-brain': 'ai_brain',
  '/smart-planner': 'smart_planner',
  '/placement-os': 'placement_os',
  '/learning-os': 'learning_os',
  '/roadmap': 'roadmap',
  '/ai': 'ai',
  '/shayla': 'ai',
  '/ai-settings': 'ai_settings',
  '/shayla-memory': 'shayla_memory',
  '/ai-playground': 'ai_playground',
  '/playground': 'ai_playground',
  '/ai-benchmark': 'ai_benchmark',
  '/benchmark': 'ai_benchmark',
  '/german': 'german',
  '/coding-mentor': 'coding_mentor',
  '/career-intelligence': 'career_intelligence',
  '/integrations': 'integrations',
  '/analytics': 'analytics',
  '/reports': 'reports',
  '/dsa-tracker': 'dsa_tracker',
  '/skillrack': 'skillrack',
  '/aptitude': 'aptitude',
  '/sql': 'sql',
  '/cscore': 'cscore',
  '/cs-core': 'cscore',
  '/projects': 'projects',
  '/resume': 'resume',
  '/interview-coach': 'interview_coach',
  '/interview': 'interview_coach',
  '/applications': 'applications',
  '/calendar': 'calendar',
  '/placement-calendar': 'placement_calendar',
  '/companies': 'companies',
  '/skill-tree': 'skill_tree',
  '/achievements': 'achievements',
  '/history': 'history',
  '/settings': 'settings',
  '/admin': 'admin',
  '/mock-interview-os': 'mock_interview_os',
  '/company-intelligence': 'company_intelligence',
  '/portfolio-os': 'portfolio_os',
  '/ai-mentor': 'ai_mentor',
};

export function navigateToPath(path: string): void {
  if (window.location.pathname === path) return;
  window.history.pushState({}, '', path);
  window.dispatchEvent(new PopStateEvent('popstate'));
}
